# FILEPATH: /Users/reneval/Development/nawaltni/places/config.toml

environment = "development"

[postgres]
host = "localhost"
port = 5432
database = "tracker"
user = "postgres"
password = "postgres"
run_migrations = true
ssl = false

[grpc]
host = "0.0.0.0"
port = 50051

[http]
host = "0.0.0.0"
port = 8080

[places]
host = "localhost"
port = 50052

[auth]
host = "localhost"
port = 50053

[bigquery]
project_id = "nawalt"
dataset_id = "mtc"
