# FILEPATH: /Users/reneval/Development/nawaltni/places/config.toml

environment = "development"

[postgres]
host = "db"
port = 5432
database = "tracker"
user = "postgres"
password = "postgres"
run_migrations = true

[grpc]
host = "0.0.0.0"
port = 50051

[places]
host = "places"
port = 50051
