version: "3.8"
services:
  db:
    platform: linux/amd64
    image: postgis/postgis:latest
    container_name: tracker_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "5432:5432"
  tracker:
    platform: linux/amd64
    build:
      context: .
      args:
        - DEPLOY_KEY=${DEPLOY_KEY}
    container_name: tracker
    environment:
      - TRACKER_POSTGRES_HOST=${POSTGRES_HOST}
      - GOOGLE_APPLICATION_CREDENTIALS=/code/application_default_credentials.json # for gcloud
    depends_on:
      - db
    ports:
      - "8001:8080"
      - "50051:50051"
    volumes:
      - ./config.toml:/code/config.toml # for using config file from local machine
      - ~/.config/gcloud/application_default_credentials.json:/code/application_default_credentials.json # for gcloud
