deployment:
  image: tracker
  tag: 0.1.0

name: tracker

replicas: 2

resources:
  requests:
    memory: 100Mi
    cpu: 50m
  limits:
    memory: 300Mi
    cpu: 150m

port: 8080

servicePort: 80

secret:
  create: true
  monitoring: "apps-metrics"
  postgresPassword: "" # inject from cmd --set secret.postgresPassword=

env:
  config:
    environment: production

grpc:
  host: "0.0.0.0"
  port: 50051
  servicePort: 50051

http:
  host: "0.0.0.0"
  port: 8080
  servicePort: 80

places:
  host: "places"
  port: 50051

ingress:
  domain: mtc.nawalt.com

postgres:
  host: nawalt-do-user-16514974-0.c.db.ondigitalocean.com
  port: 25060
  user: tracker
  db: tracker
  ssl: true
  migrate: true

bigquery:
  project_id: nawalt
  dataset_id: mtc
