name: tracker
replicas: 1

deployment:
  image: tracker
  tag: 0.1.0

ingress:
  domain: staging.nawalt.com

http:
  port: 8080
  servicePort: 80

resources:
  requests:
    memory: 50Mi
    cpu: 50m
  limits:
    memory: 100Mi
    cpu: 100m

grpc:
  host: "0.0.0.0"
  port: 50051
  servicePort: 80

secret:
  create: false
  monitoring: "apps-metrics"
  postgresPassword: "" # inject from cmd --set secret.postgresPassword=

env:
  config:
    environment: development

postgres:
  region: us-east1
  instance: nawalt-staging
  user: tracker
  host: localhost
  port: 5432
  db: tracker
  migrate: true

places:
  host: "places"
  port: 80

auth:
  host: "auth"
  port: 50051

bigquery:
  project_id: nawalt
  dataset_id: staging