deployment:
  image: tracker
  tag: 0.1.0

name: tracker

replicas: 2

resources:
  requests:
    memory: 50Mi
    cpu: 50m
  limits:
    memory: 300Mi
    cpu: 150m

port: 8080

servicePort: 80

secret:
  create: false
  monitoring: "apps-metrics"

env:
  config:
    environment: development

grpc:
  host: "0.0.0.0"
  port: 50051
  servicePort: 50051

places:
  host: "places"
  port: 80