deployment:
  image: tracker
  tag: 0.1.0

name: tracker

replicas: 1

resources:
  requests:
    memory: 50Mi
    cpu: 50m
  limits:
    memory: 300Mi
    cpu: 150m

port: 8080

servicePort: 80

secret:
  create: yes
  monitoring: "apps-metrics"

env:
  config:
    environment: development

grpc:
  host: "0.0.0.0"
  port: 50051
  servicePort: 50051

http:
  host: "0.0.0.0"
  port: 8080
  servicePort: 80

places:
  host: "places"
  port: 80

ingress:
  domain: dev.nawalt.com

postgres:
  host: nawalt-dev-do-user-1811587-0.c.db.ondigitalocean.com
  port: 25060
  user: tracker
  db: tracker
  ssl: true
  migrate: true