package domain

// PhoneMeta holds data about the phone that is reporting the user position.
type PhoneMeta struct {
	ID         string `json:"id"`          // Unique identifier of the phone in the platform
	DeviceID   string `json:"device_id"`   // Unique device identifier generated by the phone app
	Brand      string `json:"brand"`       // Brand of the phone
	Model      string `json:"model"`       // Model of the phone
	OS         string `json:"os_version"`  // Operating System version
	AppVersion string `json:"app_version"` // App version
	Carrier    string `json:"carrier"`     // Carrier name
	Battery    int    `json:"battery"`     // Battery level
}
