package domain

// PhoneMeta holds data about the phone that is reporting the user position.
type PhoneMeta struct {
	ID         string `json:"id,omitempty"`          // Unique identifier of the phone in the platform
	DeviceID   string `json:"device_id,omitempty"`   // Unique device identifier generated by the phone app
	Brand      string `json:"brand,omitempty"`       // Brand of the phone
	Model      string `json:"model,omitempty"`       // Model of the phone
	OS         string `json:"os_version,omitempty"`  // Operating System version
	AppVersion string `json:"app_version,omitempty"` // App version
	Carrier    string `json:"carrier,omitempty"`     // Carrier name
	Battery    int    `json:"battery,omitempty"`     // Battery level
}
