apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name | quote }}
data:
  environment: {{ .Values.env.config.environment | quote }}
  grpcHost: {{ .Values.grpc.host | quote }}
  grpcPort: {{ .Values.grpc.port | quote }}
  postgresUser: {{ .Values.postgres.user | quote }}
  postgresHost: {{ .Values.postgres.host | quote }}
  postgresPort: {{ .Values.postgres.port | quote }}
  postgresDB: {{ .Values.postgres.db | quote }}
  postgresMigrate: {{ .Values.postgres.migrate | quote }}
  postgresSSL: {{ .Values.postgres.ssl | quote }}
  placesHost: {{ .Values.places.host | quote }}
  placesPort: {{ .Values.places.port | quote }}
  authHost: {{ .Values.auth.host | quote }}
  authPort: {{ .Values.auth.port | quote }}
  
