apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cert-manager-global
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
  name: {{ printf "%s-grpc" .Values.name }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ printf "%s-grpc" .Values.ingress.domain }}
    http:
      paths:
      - path: /nawalt.tracker.v1.TrackingService
        pathType: Prefix
        backend:
          service:
            name: "{{ .Values.name }}"
            port:
              number: {{ .Values.grpc.servicePort }}
  tls:
    - hosts:
        - "{{ .Values.ingress.domain }}"
      secretName: "{{ .Values.ingress.domain }}-tls"
