{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name | quote }}
type: Opaque
stringData:
  postgresPassword: {{ .Values.secret.postgresPassword | quote }}
{{- end }}
