apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}"
  labels:
    app: "{{ .Values.name }}"
    monitor: "true"
spec:
  type: NodePort
  ports:
    - name: grpc
      protocol: TCP
      port: {{ .Values.grpc.servicePort }}
      targetPort: {{ .Values.grpc.port }}
    - name: http
      protocol: TCP
      port: {{ .Values.http.servicePort }}
      targetPort: {{ .Values.http.port }}
  selector:
    app: "{{ .Values.name }}"
