
# Query - Report User Position

POST https://mtc.nawalt.com/api/tracker/users/position/batch

[
    {
        "clientId": "2",
        "location": {
            "latitude": 12.1015186, "longitude": -86.2658697
        }, 
        "metadata": 
            {
                "device_id": "4b63cac51d5e03ec"
            },
        "refId": "1",
        "timestamp": "2024-05-08T01:02:49Z",
        "userId": "2"
    }
]

###

POST https://mtc.nawalt.com/api/tracker/users/position/batch

[
    {
        "clientId": "2",
        "location": {
            "latitude": 12.0983826, "longitude": -86.2691941
        }, 
        "metadata": 
            {
                "device_id": "4b63cac51d5e03ec"
            },
        "refId": "1",
        "timestamp": "2024-05-08T01:02:49Z",
        "userId": "2"
    }
]