
# Query - Report User Position

POST https://mtc.nawalt.com/api/tracker/users/position/batch

[
    {
        "clientId": "2",
        "location": {
            "latitude": 12.1015186, "longitude": -86.2658697
        }, 
        "metadata": 
            {
                "device_id": "4b63cac51d5e03ec"
            },
        "refId": "1",
        "timestamp": "2024-05-08T01:02:49Z",
        "userId": "2"
    }
]

###

POST https://mtc.nawalt.com/api/tracker/users/position/batch

[
    {
        "clientId": "2",
        "location": {
            "latitude": 12.0983826, "longitude": -86.2691941
        }, 
        "metadata": 
            {
                "device_id": "4b63cac51d5e03ec"
            },
        "refId": "1",
        "timestamp": "2024-05-08T01:02:49Z",
        "userId": "2"
    }
]

###

GET http://localhost:8080/users/7bc2176e-e888-4a2e-ad7f-0b89473a4cad/position/history?since=2024-05-13T01:02:49Z&limit=200